### ISSUE TITLE
Pregunta sobre modelos

### ISSUE THREAD

**Issue by v4rgas** [IIC2213-PUC/IIC2213-2023-1#1]
Si tengo
$$\Sigma = \{a,b,c,d\}$$

Los modelos de $\Sigma$ son las valuaciones tal que
$$models(\Sigma) = (  \sigma | \sigma(a \wedge b \wedge c \wedge d)=1)$$
?
Me confunde porque en la pregunta 3 de la tarea no hay ninguna valuacion que satisfaga en el caso que fuera asi

**Comment by seba-bug** [comment]
Hola
Efectivamente, los modelos de un conjunto son las valuaciones que satisfacen a todas las fórmulas al mismo tiempo. Por lo tanto, si $\Sigma=\\{\varphi_1,\varphi_2,\varphi_3,\varphi_4\\}$, y no existe valuación que satisfaga a todas esas fórmulas (i.e. $\Sigma$ es inconsistente), entonces
$$\text{models}(\Sigma)=\varnothing$$
Ahora el desafío es que encuentres subconjuntos no redundantes de $\Sigma$ que tengan los mismos modelos, i.e. que sean inconsistentes.
Abrazo

**Comment by v4rgas** [comment]
entonces no deberia decir en el enunciado que es una conjunción de literales en vez de una disyunción?
