### ISSUE TITLE
[Tareas] Citar desarrollo ajeno

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2213-PUC/IIC2213-2023-1#10]
Hola profe, si desarrollo una pregunta de una tarea basandome muucho en el desarrollo de una pregunta similar que pille en un texto guía por ejemplo, basta con mencionar en alguna parte de mi desarrollo algo asi como "inspirado en la página x del libro x"? Si la respuesta es no, agradezco cualquier orientación de cómo hacerlo bien.

Un abrazo.

**Comment by seba-bug** [comment]
Sí, con eso está bien. Lo importante es que la solución que hagas la escribas tú, con tus palabras. Da lo mismo si la viste textual. Recuerda que nos interesa que aprendan y sea una instancia para que piensen en las técnicas
