### ISSUE TITLE
[T2] P2: Duda sobre resolución

### ISSUE THREAD

**Issue by crisasm01** [IIC2213-PUC/IIC2213-2023-1#12]
Hola!

En la pregunta 2 se pide explicar un procedimiento que utilice resolución. Debe ser exactamente la regla de resolución vista en clases, con todas las condiciones previas? O se puede modificar un poco para determinar tautología, siendo en esencia el mismo procedimiento? No sé si me hice entender, pero no quiero ser muy explícito ya que si doy más detalle estaría dando mi desarrollo.

Saludos!

**Comment by seba-bug** [comment]
Hola!
La idea es usar resolución tal como lo vimos (dado que el sistema deductivo que vimos tiene garantías teóricas, a saber, es correcto y completo). Escríbeme al mail para ver lo que planeas hacer.
Abrazo

**Comment by EleaTriesToCode** [comment]
Sobre la misma pregunta, creo que somos muchos a tener otra duda :

En el caso de que la formula considerada NO es tautologia, nuestro metodo debe permitirnos concluirlo con plena certeza también ?
Quiero decir que si elaboramos un método con resolucion que sea algo como : "si phi es tautologia entonces dado mi método puedo obtener este resultado preciso, y si lo hago es tautologia", seria suficiente ?
Porque en este caso si es que phi no es tautologia el método no nos conduce a este "resultado preciso" - pero existe siempre la duda de que eso viene no del hecho que la formula no es una tautologia, sino de que somos incapaces de llegar al resultado preciso aplicando nuestro método... Para probar que phi no sea una tautologia me parece que debemos encontrar un contra-ejemplo en algun momento, y que cualquier método basado en intentar probar inconsistencia de un conjunto (como resolucion) no sirve en este caso... o no ?

No sé si lo explico bien, pero tengo esta duda sobre la "potencia" del método a encontrar en esta pregunta :0
Saludos :)

**Comment by seba-bug** [comment]
Hola!
En corto: el método tiene que decir SI o NO. Y no es necesario que sea un algoritmo detallado, basta con una explicación justificada de qué le haces a $\varphi$ y qué debieras poder conseguir para concluir la respuesta.

Cuando vimos resolución vimos un resultado de equivalencia entre poder deducir cierta cosa por resolución y concluir que el conjunto original satisface cierta condición. Ese teorema es un si y solo si, por lo puedes usar para ambos casos: que la fórmula sea tautología y que no. Por lo tanto, si usas resolución, como es completo y correcto, puedes responder SI o NO ante una fórmula cuando la testeas para ver si es tautología. La pega es ver cómo adaptar el $\varphi$ para que te sea útil resolución, porque no vimos nada que usara tautologías como tal.

Creo que la confusión puede venir del hecho de que si uno a mano no es capaz de deducir algo desde un conjunto usando resolución, uno no puede concluir que no se puede. Pero en el contexto de un método para un conjunto finito de variables, podrías tener una maquinita que te revisa todas las deducciones posibles (después de cierto rato, empiezas a obtener cosas equivalentes a cosas que ya habías deducido, no cierto?). Entonces un método mecánico puede decir a ciencia cierta "sí se puede deducir esto" o "no se puede deducir esto". En términos de la materia nueva: el problema de ver si podemos deducir por resolución algo específico desde un conjunto es decidible porque hay un algoritmo para hacerlo. ¿Se entiende?

Abrazo
