### ISSUE TITLE
[T2 P1] Duda sobre la definición de isomorfismo entre grafos

### ISSUE THREAD

**Issue by kiwivolador** [IIC2213-PUC/IIC2213-2023-1#13]
El enunciado dice que "dos grafos $G_1 = (V_1, E_1)$ y $G_2 = (V_2, E_2)$ son isomorfos, denotado por $G_1\cong G_2$, si existe una biyección $f : V_1 \rightarrow V_2$ tal que para todo $\set{a,b} \in E_1$ se tiene que $\set{a,b} \in E_1 \quad \text{si y solo si} \quad \set{f(a), f(b)} \in E_2$

¿No debería ser "dos grafos $G_1 = (V_1, E_1)$ y $G_2 = (V_2, E_2)$ son isomorfos, denotado por $G_1\cong G_2$, si existe una biyección $f : V_1 \rightarrow V_2$ tal que para todo $a,b \in V_1$ se tiene que $\set{a,b} \in E_1 \quad \text{si y solo si} \quad \set{f(a), f(b)} \in E_2$?

Gracias de antemano c:

**Comment by seba-bug** [comment]
Hola Kiwi
Tienes razón, ahora subiré el arreglo. En definitiva, $a,b$ son vértices del dominio de $f$.
Abrazo

**Comment by kiwivolador** [comment]
arigatou!
