### ISSUE TITLE
T2 P3 - Input vacío

### ISSUE THREAD

**Issue by JuanIke** [IIC2213-PUC/IIC2213-2023-1#14]
Hola buenas, me preguntaba si en el caso de un input vacío, se debe considerar como correcto de parte de la máquina de turing, ya que la cantidad de 0 y 1 son iguales (ninguno). O debemos rechazarlo?

**Comment by sofiaemd** [comment]
Hola! En ese caso el input debiera ser aceptado, ya que como mencionas tiene igual cantidad de 0's y 1's
¡Éxito con la tarea!

**Comment by JuanIke** [comment]
Yaa, muchas graciass
