### ISSUE TITLE
T2 - Duda sobre si que hay que demostrar teoremas vistos en clase

### ISSUE THREAD

**Issue by MTaisa** [IIC2213-PUC/IIC2213-2023-1#15]
Hola, una consulta, hay que demostrar que por ejemplo que el teorema de correctitud de resolución es verdad?? o podemos llegar y decir como: "por correctitud de resolución..."

**Comment by sofiaemd** [comment]
Hola!!
Pueden usar todos los teoremas vistos en clases, siempre que se cumplan todas las hipótesis.
Éxito con la tarea! :)
