### ISSUE TITLE
T2-P3 Eficiencia de la máquina de Turing

### ISSUE THREAD

**Issue by MTaisa** [IIC2213-PUC/IIC2213-2023-1#16]
Hola, una pregunta, hay algún requisito de exigencia para la máquina de Turing?? resulta que la mía cumple, pero siento que igual es lenta, no sé muy bien en verdad con que compararla para ver si en verdad es un problema. Es posible saber de que largo serán los inputs??

**Comment by sofiaemd** [comment]
Hola!
No hay exigencia para la velocidad, ningún input será ridículamente largo.
Éxito con la tarea :)
