### ISSUE TITLE
T3 P1 Duda de enunciado

### ISSUE THREAD

**Issue by juanelsch** [IIC2213-PUC/IIC2213-2023-1#18]
Hola, estaba viendo la tarea y no me queda muy claro lo que debemos describir en la pregunta 1) a) i). Cuando nos piden una descripción de la máquina que queda codificada en X ¿se refiere a que debemos ver qué máquina es la que se codifica como X para que efectivamente se cumpla que la máquina D decida a H?

Gracias de antemano

**Comment by ssoliva** [comment]
Hola! Leyendo esta respuesta me surgio la duda si es que a partir del último punto, la construcción de X puede tener pasos indecidibles, esto es, si cada paso de X debe poder operarse mediante una TM.

Gracias!

**Comment by seba-bug** [comment]
No sé a qué te refieres con "pasos indecidibles"... las máquinas son deterministas y tienen su funcionamiento bien definido. Otra cosa es que hay lenguajes indecidibles. Acá asumimos que $A$ es decidible y por lo tanto hay una máquinita $M_A$ que lo decide. Puedes usar como tú quieras esa máquina porque se supone que existe y es buenarda.

La máquina X debiera usar adentro a la máquina $M$... no nos preocupamos de cómo funciona esa máquina. $X$ se le pasa a $M_A$ y es ella la que decide si $X$ es "bueno o malo"... no sé si se entiende (no puedo dar más detalles sin soplar qué hace $X$).

**Comment by EleaTriesToCode** [comment]
Hola !

Me junto a esta issue con otra pregunta de enunciado para la pregunta P1.a . Al leer el enunciado y este issue, parece que lo que se debe dar a M_A es solo la codificación de X... Pero como el lenguaje A se compone de palabras de forma (M,w) me parece que el input de M_A debería ser no X sino que (X, z) dónde z es una palabra que también debemos definir.  

No me parece que hace sentido decir que M_A acepta una máquina sola, ya que no hace sentido decir que una máquina sola pertenece a A. Por ende, contesté la pregunta considerando como input de M_A una pareja (X, z).

No sé si eso era implicito en el enunciado o si hay algo que entiendo muy mal ? :0

Agradezco su ayuda :D

**Comment by juanelsch** [comment]
Hola, con respecto a esta pregunta, que pasa si la maquina Ma que decide a A recibe como input (M, w) tal que M no se detiene con w? Acepta Ma, rechaza o no se detiene?

**Comment by sofiaemd** [comment]
Hola, Si una máquina no se detiene con un input entonces no lo acepta, por lo tanto Ma rechazaría.
Éxito con la tarea!
