### ISSUE TITLE
T3 P3 consulta sobre 3SAT

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2213-PUC/IIC2213-2023-1#19]
Hola profe, esperando que se encuentre bien, quería confirmar que estoy interpretando bien el problema 3SAT en la p3. Actualmente estoy asumiendo que $3SAT =$ { $\varphi \in L\(P\)$ | $\varphi$ esta en $3CNF$ y $\varphi$ es satisfacible}.

Desde ya gracias.

**Comment by seba-bug** [comment]
exacto! es el problema que vimos en clases
