### ISSUE TITLE
T1 - Pregunta sobre posible error de enunciado

### ISSUE THREAD

**Issue by MTaisa** [IIC2213-PUC/IIC2213-2023-1#2]
Holaa, una preguntita, en la pregunta 1 del enunciado sale lo siguiente:

<img width="1006" alt="Screen Shot 2023-03-16 at 09 35 39" src="https://user-images.githubusercontent.com/89215238/225619116-005ec66d-be0d-48d9-a484-f6f4c5378c3d.png">
Pero la fórmula que mencionan como ejemplo no es la misma que luego se desarrolla en el árbol sintáctico, quería saber si es un error o estoy pasando algo por alto??

**Comment by seba-bug** [comment]
Toda la razón, se me fue arreglar la fórmula. Ahí subí la versión 2.0 con el arreglo
