### ISSUE TITLE
T3 P3 sobre definición de PE

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2213-PUC/IIC2213-2023-1#22]
Hola profe, esperando que se encuentre bien, quería preguntar si dada la corrección que mencionó por mail del enunciado, la definición de PE quedaría como:

$PE =${ $(A, \vec{b}) | A$ de $m \times n$, $\vec{b}$ de $m \times 1$ y existe un vector $\vec{x}$ de $n \times 1$ tal que $A\vec{x} \leq \vec{b}$ }

Pero me pasa que siento que si fuera asi nada cambia, por lo que no me da mucha confianza asumir esta definición. Agradezco cualquier orientación al respecto.

**Comment by sofiaemd** [comment]
Exacto! No afecta mucho, pero estaba al revés en el enunciado
Éxito con la tarea!
