### ISSUE TITLE
T3 Duda: probar una reducción

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2213-PUC/IIC2213-2023-1#23]
Hola! Tenia una duda sobre la reducción de mapeo. Para hacer una reduccion de L1 a L2 tiene que existir un f(w) tal que 
w esta en L1 ssi f(w) en L2

Me confunde cómo demostrar esto de derecha a izquierda. En esta dirección tengo que asumir que w puede ser cualquier palabra? Porque siento que si (1) asumo que el w de f(w) lo saqué de L1 no tiene mucho sentido hacer la demostración hacia la derecha, pero (2) me acuerdo que mencionamos en clases que, si bien todas las palabras de L1 tienen "imagen" en L2, no todas las palabras de L2 necesariamente tienen "preimagen" en L1.

**Comment by sofiaemd** [comment]
Hola!!
Claro, es un poco confuso ese sentido de la doble implicancia, para eso te recomiendo dos cosas. Opción 1, hacerlo por contrarecíproca, es decir puedes probar que si w no está en L1, entonces f(w) tampoco. Sin embargo, a veces eso no es lo más fácil, especialmente si definiste f explícitamente. En esos casos te recomiendo opción 2, notar cómo son los elementos en la imagen de f, fíjate que te basta probar lo pedido para esos, ya que no tienes idea qué pasa fuera de la imagen de la función.
Espero que con eso haya quedado más claro.
Éxito con la tarea!
