### ISSUE TITLE
T3 P1.b Demostrar que D decide H

### ISSUE THREAD

**Issue by tomasgbailon** [IIC2213-PUC/IIC2213-2023-1#24]
No entiendo a qué se refiere con que D decide H. Si se refiere a que D es una máquina tal que H es su lenguaje aceptado y se detiene en todo input ¿No es esto falso ya que en clases de demostró que Halting es indecidible? O hay algo que no estoy viendo

**Comment by sofiaemd** [comment]
Hola!!
Exacto!! La idea es llegar a una contradicción, es decir, si la máquina Ma existe, entonces algo falso ocurre, en este caso, eso sería tener una máquina que decide H. Espero que con eso quede más claro
¡Éxito con la tarea!
