### ISSUE TITLE
T4 P2 (Ciclo simple dirigido)

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2213-PUC/IIC2213-2023-1#26]
Hola, buenos días/tardes/noches

Tengo una duda con la definición de ciclo simple 

![image](https://github.com/IIC2213-PUC/IIC2213-2023-1/assets/42182095/256e8ce7-35b5-439e-9fbc-8c89f374897e)

Mi duda es, un clique de al menos 3 nodos tiene un ciclo simple?

gracias de antemano,
Abrazos :hugs:

**Comment by Huasito-Appel** [comment]
Up

**Comment by sofiaemd** [comment]
Holaa!
Creo que esto lo dejaremos para que ustedes lo prueben 😅 Para eso te recomiendo pensar cómo se podría construir el ciclo simple..
¡Éxito con la tarea!
