### ISSUE TITLE
T4 P2 (definición de clique)

### ISSUE THREAD

**Issue by tomasgbailon** [IIC2213-PUC/IIC2213-2023-1#28]
Tengo la duda sobre si un grafo que es un clique implica que cada nodo también está conectado consigo mismo (autoloop), o solo se refiere a que existen aristas en ambas direcciones para nodos distintos

**Comment by sofiaemd** [comment]
Hola!
Sí, la definición es que se tienen todas las aristas posibles, en particular esto incluye los loops :)
¡Éxito con la tarea!
