### ISSUE TITLE
T4P3 (Definicion de nuevas constantes)

### ISSUE THREAD

**Issue by 0DASAC** [IIC2213-PUC/IIC2213-2023-1#29]
No me queda claro si en las estructuras que devemos definir solo podemos usar {c,f} o si podemos definir mas constantes.

**Comment by seba-bug** [comment]
Hola!
No pueden agregar cosas al vocabulario... la idea es trabajar con L-estructuras y L-fórmulas dada el vocabulario fijo. Ahora, sí se pueden definir cosas usando lo que ya tienen... por ejemplo guardar en una variable un valor que te interese (con un existe, por ejemplo).
