### ISSUE TITLE
Tarea 1 Pregunta 2: Duda sobre demostraciones

### ISSUE THREAD

**Issue by v4rgas** [IIC2213-PUC/IIC2213-2023-1#3]
En la pregunta definen

$$\sigma_1 \wedge \sigma_2(p) = min(\sigma_1(p), \sigma_2(p))$$

luego nos dan valores para $\sigma_1, \sigma_2$

por que no basta con usar la definicion para saber que daria evaluar con ciertos valores?

no comprendo que es lo que hay que demostrar, creeria que evaluar la funcion ya hace que los valores sean los que se mencionan
ej
min(0,1) = 0
min(1,1) = 1

o estoy enteniendo algo mal sobre este minimo?

**Comment by seba-bug** [comment]
Hola
Los valores que se dan de $\sigma_1,\sigma_2$ son un ejemplo, para que vean cómo funciona. Es por si acaso la definición con $\min$ no se entiende

**Comment by v4rgas** [comment]
lo digo porque, por ejemplo, en la parte a) piden demostrar que si ambos valores son 1 entonces el minimo es 1 pero eso es simplemente evaluar o no?

**Comment by seba-bug** [comment]
Aah ya entendí tu duda. Ojo que lo que se pide en (a) es para una **cláusula de Horn** $\varphi$. La definición que se da en el enunciado habla de variables atómicas (cualquier $p\in P$). Lo que hay que demostrar ahí es que para los distintos tipos de cláusula de Horn, se cumple que al combinar dos valuaciones que la satisfacen, se obtiene una nueva valuación que también la satisface. ¿Se entiende? Date un ejemplo de cláusula de Horn y arma un ejemplo de valuaciones que la satisfagan, y verifica la propiedad. Eso te puede dar intuición.

**Comment by v4rgas** [comment]
creo que me esta costando un poco entender que tengo que hacer exactamente

lo que veo en la a) es que estan definiendo una funcion que devuelve el minimo de las evaluaciones, luego me dan los valores para cada una de las valuaciones entonces se que por definicion este va a ser el minimo de ambos, en este caso 1

disculpe por preguntar tantas veces pero es que de verdad me esta costando

**Comment by seba-bug** [comment]
Dadas las dos valuaciones $\sigma_1$ y $\sigma_2$, se define una nueva valuación $\sigma_3$ (llamémosle así para facilitar la notación), que asigna a cada variable atómica el valor mínimo que asignan $\sigma_1$ y $\sigma_2$. Es decir, por ejemplo, para $P=\\{p,q\\}$ consideremos

$$ \sigma_1(p)=1,\quad \sigma_1(q)=1$$

$$ \sigma_2(p)=0,\quad \sigma_2(q)=1$$

$$ \sigma_3(p)=0,\quad \sigma_3(q)=1$$

La valuación $\sigma_3$ es una valuación como cualquier otra, se evalúa recursivamente para poder dar el valor de verdad de una fórmula compuesta. Por ejemplo,  si $\varphi_1=p\rightarrow q$ y $\varphi_2=p\vee q$, entonces

$$\sigma_3(\varphi_1)=0,\qquad \sigma_3(\varphi_2)=1$$

La propiedad que hay que demostrar es que si la fórmula analizada **es una cláusula de Horn**, entonces cuando dos valuaciones la satisfacen, la valuación combinada que se construye a partir de ellas también satisface a la fórmula. Ojo, esto no es cierto si la fórmula no es cláusula de Horn. Por eso esta propiedad no es trivial... tienen que usar la estructura de cláusula de Horn para concluir.

Estrategia: asume como hipótesis que tienes dos valuaciones que satisfacen una cláusula de Horn $\varphi$. Debes demostrar que la valuación combinada también la satisface. Ahí usas la estructura que tiene $\varphi$.

¿Se entiende? Si estás muy complicado, escríbeme un mail y podemos verlo por zoom.
Abrazo

**Comment by v4rgas** [comment]
no debería $\sigma_3(\varphi_1)$ ser igual a 1 ya que el min(p) es 0 y el minimo de q es 1, haciendo que $p \rightarrow q = 1$

**Comment by seba-bug** [comment]
Me equivoqué! Ahí cambié la fórmula... quería mostrar que se evalúa como es usual esa valuación y puede generar 0 o 1 según la sintaxis de la fórmula.

**Comment by v4rgas** [comment]
estoy entendiendo mejor!! lo que me ayudaria ahora seria un ejemplo de una formula que no sea de horn la cual no cumpla con esta propiedad

creo que con eso ya me quedaria claro

**Comment by seba-bug** [comment]
Por ejemplo, tomemos $\varphi=p\vee q$, que es satisfecha por las valuaciones

$$\sigma_1(p)=1\quad\sigma_1(q)=0$$

$$\sigma_1(p)=0\quad\sigma_1(q)=1$$

Dadas esas dos valuaciones, la combinada es

$$\sigma_1\wedge\sigma_2(p)=0\quad\sigma_1\wedge\sigma_2(q)=0$$

y tenemos que

$$\sigma_1(\varphi)=1,\ \sigma_2(\varphi)=1,\quad\text{pero }\sigma_1\wedge\sigma_2(\varphi)=0$$

**Comment by v4rgas** [comment]
ya entendi!!! muchisimas gracias

**Comment by ignaciomansuy** [comment]
Profe no me queda claro porqué $\sigma_1\wedge\sigma_2(\varphi)=0$

Mi razonamiento es el siguiente, tenemos que:
```math
\sigma_1\wedge\sigma_2(\varphi) = min\{\sigma_1(\varphi), \sigma_2(\varphi)\}
```
y sabemos que $\sigma_1(\varphi)=1$ y que $\sigma_2(\varphi)=1$
lo que implica que 
```math
\sigma_1\wedge\sigma_2(\varphi) = min\{1, 1\} = 1
```

No logro ver qué parte de esto está fallando

**Comment by seba-bug** [comment]
En en el enunciado se especifica que la valuación usa el mínimo cuando evalúa variables (fórmulas atómicas), no fórmulas compuestas. Es una valuación como cualquier otra, solo que la asignación de las variables atómicas depende de las dos valuaciones conocidas. Cuando evalúa fórmulas compuestas manda la semántica que vimos para cada conectivo.
¿Se entiende?

**Comment by ignaciomansuy** [comment]
Si, me quedó claro, gracias profe
Dejo igual el edit anterior por si algún compañero le sirve
