### ISSUE TITLE
T4 P3 Duda sobre materia

### ISSUE THREAD

**Issue by v4rgas** [IIC2213-PUC/IIC2213-2023-1#30]
Al definir una L-estructura que tenga los numeros naturales ($\mathfrak{A} = \langle \mathbb{N} \rangle$) puedo asumir que puedo usar los operadores que conozco para los naturales? por ejemplo decir que f(x) = x^2 o f(x) = 1-x y cosas de este tipo? o solo puedo usar los operadores que estan dentro de mi estrucutra para definir la funcion?

**Comment by seba-bug** [comment]
Hola!
Al definir la interpretación de los símbolos de predicado, puedes darle la interpretación que quieras. En definitiva, estás diciendo qué imagen tiene un natural n cuando evaluas f(n). Puede ser n^2 o 1-n como dices
