### ISSUE TITLE
T4 P3 [Duda materia]

### ISSUE THREAD

**Issue by milosoria** [IIC2213-PUC/IIC2213-2023-1#31]
Hola, tengo la siguiente duda. En clases vimos que la función de una estructura tiene que cumplir que:
![image](https://github.com/IIC2213-PUC/IIC2213-2023-1/assets/61996784/6e7d85fa-cbec-418c-89c6-f976aaed6263)
Entonces la función no puede tener un recorrido que corresponda a un subconjunto del dominio, como por ejemplo:

```latex
f: \mathbb{R} \rightarrow \mathbb{R}^+
```

**Comment by seba-bug** [comment]
Hola!
La función no necesita ser sobreyectiva (tampoco inyectiva). Eso solo exige que el "sabor" de los elementos del dominio sea tuplas de m elementos de A, y que las imágenes sean elementos de A
