### ISSUE TITLE
T4 P3 Definir f como función constante

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2213-PUC/IIC2213-2023-1#32]
Hola! Tenía la duda de si, al definir una estructura y darle significado a los símbolos, puede plantearse los símbolos f como funciones m-arias de resultado constante (por ejemplo f(x,y) = 7). Hasta ahora entiendo que no hay restricciones sobre f fuera de ser una función no más, pero también me entra la duda pq ya hay otros símbolos que representan constantes.

**Comment by seba-bug** [comment]
Hola!
ningún problema. Tal como dices, no hay restricciones sobre la f, puede no ser inyectiva ni sobre
