### ISSUE TITLE
T4 P3: duda sobre phi3

### ISSUE THREAD

**Issue by Pabloski100** [IIC2213-PUC/IIC2213-2023-1#33]
Hola, al  hacer esta pregunta me confundí con algo del phi3, como interactuá un "para todo" cuando se coloca una función del estilo f(y) = x?

Específicamente, dado un dominio A, una cierta función f tendrá un determinado dominio y recorrido (ambos subconjuntos de A, tal vez iguales a A), cuando se cuantifica una función con "para todo" en su dominio o recorrido ¿Significa eso que la función debe tener su recorrido o dominio igual a A?

Por ejemplo: dado un dominio A

para todo x. existe y. f(y) = x: No logro distinguir si esto significa "para toda imagen x en Rec(f), existe preimagen y en Dom(f) tal que f(y) = x" o  "para toda x en A, existe y en A tal que f(y) = x"

En caso de ser lo segundo, me confunde cuantificar el recorrido, porque si es "para toda x en A" siento que me están obligando usar todo A como recorrido, esto es así? (notar que en el primer caso esto no pasa, porque me limito a Rec(f), que podría incluir solo algunos elementos de A)

**Comment by seba-bug** [comment]
Super importante tu pregunta
Los para todo y los existe funcionan mirando el dominio de la L-estructura
Entonces el ejemplo que das
$$\\forall x.\\exists y. f(y)=x$$
se refiere a mirar en A si para todo elemento, hay alguno en A (puede ser el mismo) tal que f(y)=x
