### ISSUE TITLE
T4 P2: Duda con demostración y L-estructura

### ISSUE THREAD

**Issue by ssoliva** [IIC2213-PUC/IIC2213-2023-1#35]
Hola! No tengo muy claro la forma de demostrar que nuestras L-oraciones son correctas, en específico la oración:

"Observe que cada oración deben ser satisfecha por una L-estructura U si, y solo si, el grafo representado por
U cumple la propiedad modelada con dicha oración"

No me queda claro si debemos definir la estructura para un grafo, o cómo hacer ese si y sólo si, si es que me pueden orientar un poco.

Gracias!

**Comment by seba-bug** [comment]
Hola!
Ese si y solo si es para que lo tengas presente en el diseño de tus oraciones. No les pedimos demostrar que son correctas. El objetivo es que construyas una oración que represente una propiedad, de forma que esa oración sea satisfecha única y exclusivamente por todas las L-estructuras que representan grafos con dicha propiedad.
Por ejemplo, si la propiedad es "el grafo tiene al menos dos nodos diferentes", y yo propongo una oración $\phi$, esa oración será satisfecha por las siguientes estructuras:
$$\mathfrak{A}=\langle\\{0,1\\},\\{(0,1),(1,1)\\}\rangle$$
$$\mathfrak{B}=\langle\\{a,b,c\\},\\{(a,b),(b,c)\\}\rangle$$
$$\mathfrak{C}=\langle\mathbb{N},\varnothing\rangle$$
Donde el primer elemento es el dominio (los nodos) y el segundo es la interpretación de la relación $E$ de aristas. Esas tres estructuras satisfacen la oración. Esos tres son ejemplos... el si y solo si que mencionas habla de que 
(1) toda estructura que representa un grafo con al menos dos nodos diferentes, satisface $\phi$
(2) toda estructura que satisface $\phi$ representa un grafo con al menos dos nodos diferentes

¿se entiende?

**Comment by ssoliva** [comment]
Con esto me quedó super claro, muchas gracias!
