### ISSUE TITLE
T4 P3 [Duda cardinalidad]

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2213-PUC/IIC2213-2023-1#36]
Hola! 
En las oraciones, las variables "x", "y" son de dimensión 1? o pueden ser de mayor dimensión? Por ejemplo, en sigma 3, y podría ser algo del estilo y = (y1, y2, y3)? 
Muchas gracias de antemano.

**Comment by seba-bug** [comment]
Hola Ignacio
El dominio de una estructura puede ser lo que quieras mientras sea un conjunto no vacío. Por ejemplo, podría ser {1,2,3}X{a,b} y ahí tendrías tuplas como elementos para reemplazar en las variables de tus fórmulas. ¿Se entiende? No sé si a eso va la pregunta

**Comment by ignaciovilla** [comment]
Entonces para que yo pueda definir una función f(**x**) con **x** = (x1, x2) (ej: f(**x**) = x1 - x2), el dominio de mi estructura tiene que ser por ejemplo {Naturales x Naturales}, o puede ser solo los {Naturales}?
Muchas gracias de antemano

**Comment by seba-bug** [comment]
Tiene que ser el cartesiano. Ojo que si usas esa resta en la interpretación, el dominio debiera ser ZxZ para permitir negativos. Si tu estructura $\mathfrak{A}$ tiene dominio $\mathbb{Z}\times\mathbb{Z}$, puedes definir la interpretación de f como la función:
$$f^\mathfrak{A}=\\{((1,3),-2), ((0,4),-4),((5,-6),11),...\\}=\\{((a,b),a-b)\mid a,b\in\mathbb{Z}\\}$$
Pd: no olvidar que las funciones son relaciones... por eso la escribí como conjunto de tuplas, para ser más explícito en lo que estás proponiendo

**Comment by ignaciovilla** [comment]
Solo para confirmar, el resultado de esta función está en Z o en ZxZ? 
En el caso de que este en Z, no me queda tan claro porque la función es unaria, ya que en el ppt de la clase se habla sobre las "interpretaciones de las funciones m-arias". 
Esto último me confundió un poco, porque según entiendo de esa definición, en este caso el dominio de la estructura debería ser Z, con la función binaria  f : ZxZ --> Z. 
Muchas gracias de antemano.

**Comment by ignaciovilla** [comment]
Perfecto. Muchas gracias!
