### ISSUE TITLE
T5P2 Duda función biyectiva en isomorfismo

### ISSUE THREAD

**Issue by festelle** [IIC2213-PUC/IIC2213-2023-1#38]
Tengo una duda sobre la función con la que puedo definir el biyectividad. Puedo poner condiciones sobre el valor del x que recibe? Por ejemplo:

$$f(x) =  \[ \begin{cases} 
      a & x < y \\
     b & y \leq x \leq z \\
      c & z < x 
   \end{cases}
\] $$

Esta función sería considerada correcta o no es permitido?

Muchas gracias!

**Comment by sofiaemd** [comment]
Hola!
Estoy suponiendo que quieres definir una biyección para definir un isomorfismo. Si ese es el caso, esa es una función bien definida, pero no necesariamente es una biyección o un isomorfismo, eso depende der dominio y recorrido de la función y debes probarlo en cada caso.
Si eso no queda claro, tal vez podemos discutirlo con calma mañana en la ayudantía :)
