### ISSUE TITLE
Duda Materia\Tarea5

### ISSUE THREAD

**Issue by csantiagopaz** [IIC2213-PUC/IIC2213-2023-1#39]
Hola buenas tardes,

Tengo una duda cuando se va aplicar un isomorfismo en una L-Estructura se puede hacer uso de los operadores clásicos, que me refiero:

![image](https://github.com/IIC2213-PUC/IIC2213-2023-1/assets/42182095/2aa792a2-2097-44a4-a16f-62ae5b467de6)

Si en ese caso mi función h por ejemplo tuviera una multiplicación, seria valida? O obligatoriamente solo puede tener los elementos de dentro de la L-Estructura no siendo valido usar nada que no sea la igualdad, y conectivos de LPO?

**Comment by seba-bug** [comment]
Hola!
Cuando defines el isomorfismo no hay ninguna restricción en lo que puede hacer por dentro. Lo único es que debe satisfacer las "propiedades de isomorfismo": biyección del dominio al dominio, y que respete constantes, funciones y relaciones de las estructuras involucradas. 
Ahora, en esa pregunta que pones en la foto, hay que definir una fórmula que captura la noción de sucesor... en ese caso no usamos el teorema de isomorfismo porque queremos dar una fórmula como testigo de que ese concepto es definible.
