### ISSUE TITLE
Duda T1 P1 b

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2213-PUC/IIC2213-2023-1#4]
Hola me surge una duda en la parte b de la pregunta 1, bajo la definición que vimos en clases de formulas proposicionales no faltarían unos paréntesis que encierren a toda la función phi por lo tanto el largo debería ser 18 y no 16 en el ejemplo considerando esos paréntesis extra?
Gracias de antemano por la respuesta

**Comment by seba-bug** [comment]
Hola!
La fórmula es $\varphi = ((p \vee q) \rightarrow (p \wedge (\neg r)))$, que está de acuerdo a la sintaxis "rígida" con exceso de paréntesis. Esa tiene 16 símbolos en total. Ojo que los otros paréntesis del enunciado son de la función largo: $\text{la}(\varphi)$ y esos dos no se cuentan en el largo. ¿Se entiende?

**Comment by JuaniAndres** [comment]
Si entiendo, confusión mía pensé que el ejemplo del árbol sintáctico era el mismo de la pregunta b ahora todo me hace sentido
Gracias
