### ISSUE TITLE
T5P3 Duda estructura

### ISSUE THREAD

**Issue by Fuentes149** [IIC2213-PUC/IIC2213-2023-1#40]
Tengo una duda sobre si el conjunto S[L] siempre es infinito, osea es el conjunto de todas las estructuras que se pueden crear con ese vocabulario o puede ser un conjunto arbitrario de estructuras que se pueden crear con ese vocabulario?

Mucha gracias

**Comment by seba-bug** [comment]
Hola!
El conjunto S[L] siempre es infinito porque ahí están todas las estructuras posibles con L. Si fijamos un vocabulario L, independiente si tiene o no símbolos, ya tenemos infinitas estructuras en S[L] porque podemos tomar infinitos dominios diferentes para esas estructuras. ¿Se entiende?
