### ISSUE TITLE
T6 P1

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2213-PUC/IIC2213-2023-1#41]
Hola estoy un poco confundido con la notación en especifico como usar correctamente la relacion binaria y ternaria para relacionar las tablas podrían entregar un ejemplo de consulta valida para hacerme una idea de eso?

**Comment by csantiagopaz** [comment]
No sé si viste la Ayudantía de este viernes, ahí hay un ejemplo bien completito

**Comment by JuaniAndres** [comment]
No la revise muchas gracias por el dato
