### ISSUE TITLE
[T6P1.d] Duda sobre enunciado

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2213-PUC/IIC2213-2023-1#43]
Holi de nuevo :0

En la pregunta 1.d, lo que se pide es crear (si es posible) cuál de estas dos?:

1. una sola consulta phi que pueda entrgar la proyección de la i-ésima columna de R (interpretando a i como una variable)
2. i consultas phi_i, donde cada una entrega la proyección de la i-ésima columna de R, de su i correspondiente (interpretando a i como un "parámetro")

**Comment by seba-bug** [comment]
Hola
Creo que la opción 2 (es que no sé si entendí bien). Te doy un ejemplo. Si la relación $R$ se interpreta como $\\{(gato,felino),(pato,ave),(alacrán,arácnido)\\}$ y hacemos la proyección de la columna 1, entonces nos interesa obtener $\\{gato,pato,alacrán\\}$. Nos quedamos con valores sueltos que corresponden a la columna número 1 de la interpretación de la relación. Dado un $i$, pedimos la proyección de la columna número $i$, es un parámetro. ¿Se entiende?

**Comment by sopadeoliva** [comment]
Sí creo que entendí. Creo que se entiende mejor si los escribo así. Entendí que lo que se pide es como la segunda forma, verdad?:
1. $\varphi(x_1, ..., i) = ...$
2. $\varphi_i(x_1,....) = ...$
