### ISSUE TITLE
T6 P1 parte 2 Extensiones a la definición

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2213-PUC/IIC2213-2023-1#44]
Hola tengo una duda si hay algún limite con respecto a las extensiones que podemos realizar a la definición por ejemplo es valido modificar las relaciones aumentando su aridad agregando algún dato a nuestra elección o definir operaciones para la comparación de números por ejemplo <=?

**Comment by seba-bug** [comment]
Hola!
No restringimos mucho lo que puedes agregar, pero la idea es pensar ¿qué cosas de la sintaxis de la lógica de primer orden no están permitidas en las consultas conjuntivas y servirían para lograr cierta consulta que no es posible sin eso?

**Comment by seba-bug** [comment]
Claro, la idea es no modificar el vocabulario, esos símbolos son fijos

**Comment by JuaniAndres** [comment]
Perfecto entiendo muchas gracias profesor
