### ISSUE TITLE
T6 P1 d  repeticiones

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2213-PUC/IIC2213-2023-1#45]
Hola profe,
en el enunciado nos piden que hagamos una consulta tal que no tenga repeticiones. Por como entiendo que funcionan los conjuntos por definición, un elemento pertenece o no a una conjunto y no son algo relevante las 'repeteiciones'. Por lo mismo creo que hay algun planteamiento que no se si estoy entendiendo. aunque me esforzara por hacer repeticiones, no creo que pueda lograrlo, pues al final tenemos un conjunto hecho por una definición y los elementos pertenecen o no, sin de alguna forma tener repeticiones.

¿Hay algo que estoy entendiendo mal?

**Comment by seba-bug** [comment]
Hola!
Estás en lo correcto. Puse esa aclaración porque si alguien lo leía en el contexto de base de datos, podía pensar que la proyección tenía que contener cada aparición repetida como una tabla con repeticiones. Pero aquí estamos trabajando con conjuntos

**Comment by Aloncarrasco** [comment]
gracias!!
