### ISSUE TITLE
P6 Consultas Conjuntivas

### ISSUE THREAD

**Issue by juanelsch** [IIC2213-PUC/IIC2213-2023-1#46]
Tengo una duda con respecto a las consultas conjuntivas vistas en la ayudantia 11. Con respecto a la segunda la cual es la siguiente:

$\varphi (x_1, x_2, x_3) = \exists z_1, z_2, z_3. R1(x_2,  x_3, z_1) \wedge R2(x_1, z_2, z_3)$ 

Lo que no entiendo bien es como hace esta consulta para relacionar las dos tablas si es que los tres z's que se piden estan en las relaciones independientemente. A lo que voy es que la respuesta no deberia contener un z que este presente en ambas relaciones para que se cumpla lo que se pide? algo como de este estilo:

$\varphi (x_1, x_2, x_3) = \exists z_1, z_2. R1(z_1,  x_1, x_2) \wedge R2(x_1, z_1, z_3)$

dado que aca nos estariamos asegurando que $x_1, x_2$ y $x_3$ tengan la misma fecha y se cumple lo que se pide. Quizas me este confundiendo con algun concepto pero lo que no me queda claro de la respuesta de a ayudantia principalmente es como esa consulta relaciona las dos relaciones.

**Comment by ignaciovilla** [comment]
Hola! Me sumo a la pregunta

**Comment by sofiaemd** [comment]
Holaa!
Sí perdón, fue error de tipeo, lo comenté en la ayudantía, pero había olvidado arreglar el pdf T-T debería ser como tú propones

**Comment by sofiaemd** [comment]
No bueno, en realidad no es exactamente como propones, hay un error de tipeo en los subíndices de los x, deberían ser x2 y x3 en la primera relación. Altiro subo la solución de la ayudantía arreglada

**Comment by sofiaemd** [comment]
Solución arreglada!! Disculpa nuevamente por el error
