### ISSUE TITLE
T6 p1 d,e

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2213-PUC/IIC2213-2023-1#47]
Cuando nos hablan de buscar algo para la i-esima algo, el i debe ser una  "Variable" por así decirlo? de alguna forma indicamos el valor de ese i y la phi (L - formula) debe retornar la columna para ese i? o de alguna forma encontramos la formula suponiendo que ya sabemos cual es el valor de i??

**Comment by sofiaemd** [comment]
Hola! Debes suponer que tienes un i dado y con eso quieres hacer la consulta pedida en la pregunta.

**Comment by Aloncarrasco** [comment]
excelente, gracias!
