### ISSUE TITLE
T6 Pregunta 1: Uso de constantes en relaciones.

### ISSUE THREAD

**Issue by domingo2000** [IIC2213-PUC/IIC2213-2023-1#48]
Hola, resulta que en la definición del vocabulario dada para consultas conjuntivas solo incluye las relaciones de las tablas en el vocabulario, pero no incluye constantes para poder hacer fórmulas con valores constantes. Estaba viendo la definición de consulta booleana conjuntiva en wikipedia https://en.wikipedia.org/wiki/Boolean_conjunctive_query#:~:text=.,the%20facts%20in%20the%20database. y veo que ahí si hacen uso de constantes en las fórmulas. Mi duda es entonces, es el vocabulario solamente las relaciones, o es la unión entre todas las relaciones y todas las posibles constantes. En la lectura [Basics of Conjunctive Queries](https://pages.cs.wisc.edu/~paris/cs838-s16/lecture-notes/lecture1.pdf) hablan de que las fórmulas pueden tener tanto variables como constantes, por lo tanto me surge la duda acerca de la definición del vocabulario dada. Citando *The expressions* $y_1, . . . , y_n$ *are called free tuples, and contain either variables or constants*. Esto contrasta con la definción de la tarea solo tiene variables y la LPO solo deja hacer fórmulas con constantes en el vocabulario. Saludos

**Comment by seba-bug** [comment]
Hola!
En la tarea estamos usando un fragmento de consultas conjuntivas, que se aplica a vocabularios que solo tienen símbolos de relaciones. Podemos pensarla como una primera versión de las consultas conjuntivas más generales.
