### ISSUE TITLE
[Tarea 1] Pregunta 2: ejemplo y equivalencia

### ISSUE THREAD

**Issue by sopadeoliva** [IIC2213-PUC/IIC2213-2023-1#5]
Holaaa! Tenía dudas de dos preguntas:

2c) Para demostrar que una fórmula no equivale a ninguna fórmula de horn se puede mostrar con un ejemplo y explicar por qué? O tenemos que demostrarlo para una "fórmula abstracta"?

2b) Quedé medio confundida con la parte de "es equivalente a una fórmula de horn". Entiendo que podemos definir las fdH inductivamente, pero no me quedó claro si el plan es definir "una fórmula de Horn" o "una fórmula equivalente a una de Horn", o si son lo mismo. 😵‍💫

**Comment by seba-bug** [comment]
Hola!
En la 2c) puedes dar un contraejemplo concreto y en ese caso debes demostrar que tu ejemplo no se puede llevar a fórmula de Horn.
En la 2b), se pide probar una propiedad para una fórmula cualquiera $\psi$ que es equivalente a alguna fórmula de Horn desconocida. El 2b) precisamente nos muestra que no toda fórmula es equivalente a una fórmula de Horn. Del inciso 2a) sabes una propiedad de las cláusulas de Horn que puedes ocupar en este inciso.
¿Se entiende?

**Comment by seba-bug** [comment]
Exacto, esa es la idea jjjj Puedes asumir en ese inciso que la propiedad (b) ya está demostrada
Abrazo
