### ISSUE TITLE
T1P3 importante

### ISSUE THREAD

**Issue by seba-bug** [IIC2213-PUC/IIC2213-2023-1#6]
Hola wawos
Un comentario a partir de preguntas que dos de ustedes me hicieron y que están correctas en su intuición.
En la pregunta 3, inciso b, deben probar primero que todo conjunto $\Sigma$ tiene al menos un subconjunto no redundante equivalente. Esto es bien sencillo, lo pueden justificar en un par de líneas (por ej, mencionando cómo construir tal subconjunto). Una vez que prueban eso, tiene sentido hablar de fórmula necesaria para un $\Sigma$ arbitrario.
Cualquier duda nos avisan
Abrazo!

**Comment by JuanpaBC** [comment]
Hola profe, tengo la duda de si es necesario mostrar que lo que menciona para el conjunto $\Sigma$ vacío, el cual entiendo que cumple con todos los requisitos mencionados en el enunciado para ser subconjunto no redundante equivalente a sí mismo.

**Comment by seba-bug** [comment]
Sobre el conjunto $\Sigma=\varnothing$ hay un tema importante. Para ese conjunto se cumple de forma **vacua** la definición de satisfcabilidad: "para toda fórmula en $\Sigma$, $\sigma$ es modelo". Como $\Sigma$ no tiene fórmulas, esa definición se cumple para cualquier valuación (no hay niuna fórmula que chequear), por lo tanto: $\Sigma=\varnothing$ **es satisfecho por cualquier valuación**. Conclusión: lo que se puede deducir de $\Sigma$ es cualquier **tautología**.

Otra cosa distinta es cuando $\Sigma$ es contradictorio... eso significa que no hay valuación que satisfaga a todas sus fórmulas de forma simultánea... eso puede ocurrir por ej si tenemos $\Sigma=\\{\bot\\}$ o $\Sigma=\\{p\wedge\neg p\\}$. Desde esos se puede deducir cualquier cosa.
¿Se entiende?
Según esto, el conjunto $\\{p\\}$ ¿es redundante?

**Comment by JuanpaBC** [comment]
sii gracias profe!
