### ISSUE TITLE
T1 - P2

### ISSUE THREAD

**Issue by BelenSilva1204** [IIC2213-PUC/IIC2213-2023-1#8]
Hola Profe!

Para la pregunta 2 c) tengo una duda con la propiedad que podemos dar por demostrada en b), si una fórmula es equivalente a una fórmula de Horn significa que basta con que **un** par de valuaciones que hacen verdadera a la fórmula cumpla lo dicho en b) para que sea cierto? o se debe cumplir lo de b) **para todas** las combinaciones de pares de valuaciones que hacen verdadero a la fórmula para que exista una fórmula de Horn equivalente?

**Comment by seba-bug** [comment]
Hola Belén
La propiedad 2b es para toda valuación. Si cumplen el antecedente (ambas satisfacen a la fórmula), se obtiene la conclusión (la valuación combinada también satisface a la fórmula). ¿Se entiedne?
