### ISSUE TITLE
T2P1 - Demostración de correctitud

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2213-PUC/IIC2213-2023-1#9]
Hola profe, me pasa que para la pregunta 1 construí una fórmula $\varphi_{iso}$ no de una, sino armando subformulas/componentes de ella y explicando el por qué era necesaria cada una de ellas. De esta forma, me queda la duda de qué hacer con la parte del enunciado que pide demostrar la correctitud de mi construcción. No sé si por el procedimiento que le mencioné puedo considerar listo mi desarrollo de la p1 (asumiendo que expliqué bien cómo la satisfacibilidad de $\varphi_{iso}$ garantiza que $G_{1} \cong G_{2}$), o si lo que se pide al final del enunciado requiere de una demostración formal específica de correctitud. Si es el segundo caso, agradecería cualquier orientación al respecto.

Un abrazo.

**Comment by seba-bug** [comment]
Hola!
La demostración de que la construcción es correcta no es algo tan formal. Pero ojo que hay dos direcciones que demostrar. ¿Te acuerdas que en clases vimos que a partir de uan valuación podíamos construir una función de coloración? La idea es que haga en el caso de que la fórmula sea satisfacible puedas mostrar cómo se está verificando la existencia de la función $f$ que es isomorfismo. La otra dirección (existe isomorfismo y quieres probar que hay modelo para $\varphi_\text{iso}$) es esencialmente lo que explicaste... tienes que argumentar por qué existe esa valuación.
¿Se entiende?
Abrazo
